# Generated by Django 4.2.11 on 2026-01-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.RenameField(
            model_name='rides',
            old_name='shared',
            new_name='is_shared',
        ),
    ]
