# Generated by Django 4.2.11 on 2026-01-27 03:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('rides', '0002_rename_confirmed_rides_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='num_of_passengers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rides',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride', to='profiles.vehicle'),
        ),
    ]
