# Generated by Django 4.2.11 on 2026-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_rides_num_of_passengers_alter_rides_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
