# Generated by Django 4.2.11 on 2026-01-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rides_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='num_of_passengers',
            new_name='num_passengers',
        ),
    ]
