# Generated by Django 4.2.11 on 2026-01-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_rename_num_of_passengers_rides_num_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='special_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
