# Generated by Django 4.2.11 on 2026-01-28 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0006_rides_special_request_rides_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='ride_as_sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
