# Generated by Django 4.2.11 on 2026-01-28 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('rides', '0007_rides_sharers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rides',
            name='sharers',
            field=models.ManyToManyField(blank=True, related_name='shared_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rides',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='profiles.vehicle'),
        ),
    ]
